name: Build & Publish Container Image
description: Builds and publishes a docker image to the ghcr.io docker registry and updates the release description to point ot the package
author: Splunk DLT
inputs:
    publish-type:
        required: true
        description: 'Use "pre-release" to only publish a pre-release package and "release" to publish a versioned release'
    ghcr-org:
        description: GitHub organization name to use for the ghcr.io registry. If not specified, the organization the repository is in will be used.
        required: false
    ghcr-pre-release-name:
        description: Package name to use for pre-releases. In not specified, the repository name with a "-pre" suffix will be used.
        required: false
    ghcr-release-name:
        description: Package name to use for releases.  In not specified, the repository name will be used.
        required: false
    ghcr-user:
        description: Service user to use for publishing the packages
        required: true
    ghcr-pat:
        description: Personal access token of the service to use for publishing
        required: true
    github-token:
        description: Personal access token to accessing the GitHub API to perform additional release tasks (as as for updating the release description)
        required: false
runs:
    using: 'node12'
    main: 'dist/index.js'
