name: Actions Checks

on:
    push:
        paths:
            - 'actions/**'

jobs:
    actions-build-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.16.0
            - name: ensure build is up-to-date
              run: |
                  cd actions/build-publish-container
                  yarn install --frozen-lockfile
                  yarn build
                  git diff --exit-code
